version: "3.9"
services:
  web:
    build: .
    environment:
      - URL=mongodb://db:27017
      - USER=root
      - PASSWORD=root
      - DB_NAME=my_virtual_personal_trainer
    ports:
      - "8000:5000"
  db:
    restart: always
    image: "mongo:6.0.2-focal"
    ports:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=root-db
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo/mongod.conf:/etc/mongod.conf:ro
      - ./mongo/mongo-volume:/data/db

networks:
  default: